print(ord('a'))
print(chr(97))
print(ord('b'))
print(chr(98))
print(ord('c'))
print(ord('d'))
print(ord('e'))
print(ord('f'))
print(ord('g'))
print(ord('h'))
print(ord('i'))
print(ord('j'))
print(ord('k'))
print(ord('l'))
print(ord('m'))

